mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: myshop
    password: myshop2023!
    url: jdbc:mysql://myshop-database.cm6solhgg2g0.ap-northeast-2.rds.amazonaws.com:3306/myshop
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 8080
cloud:
  aws:
    s3:
      bucket: sayho-myshop-bucket
    credentials:
      access-key: AKIASXBNAYK37QIQ7KQD
      secret-key: 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
    region:
      static: ap-northeast-2
---

mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:myshop
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: test
server:
  port: 8082
