mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: myshop
    password: myshop2023!
    url: jdbc:mysql://myshop-database.cm6solhgg2g0.ap-northeast-2.rds.amazonaws.com:3306/myshop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: prod
server:
  port: 8080
